package:
    name: zeromq
    version: 4.2.2
source:
    fn: zeromq-4.2.2.tar.gz
    patches:
        - 0001-fix-installation.patch
    sha256: 5b23f4ca9ef545d5bd3af55d305765e3ee06b986263b31967435d285a3e6df6b
    url: https://github.com/zeromq/libzmq/releases/download/v4.2.2/zeromq-4.2.2.tar.gz
build:
    features:
        - cling
        - vc14 # [win and py36]
    noarch: ''
    noarch_python: false
    number: '0'
    string: 'cling_0'
    skip:  true  # [py<36]

requirements:
    build:
        - cmake
        - toolchain
        - libsodium 1.0.3 0
        - python
        - cling-patches
        - gcc-7                       # [linux and not armv7l]
    run:
        - cling-patches
        - libsodium
        - vs2015_runtime >=14.0.25420 # [win]
        - libgcc-7                    # [linux and not armv7l]
test:
    commands:
        - if exist %LIBRARY_LIB%\libzmq-mt-s-4_2_2.lib (exit 0) else (exit 1)                           # [win]
        - if exist %LIBRARY_BIN%\libzmq-mt-4_2_2.dll (exit 0) else (exit 1)                             # [win]
        - if exist %LIBRARY_LIB%\libzmq-mt-4_2_2.lib (exit 0) else (exit 1)                             # [win]
        - if exist %LIBRARY_BIN%\libzmq.dll (exit 0) else (exit 1)                                      # [win]
        - if exist %LIBRARY_LIB%\libzmq.lib (exit 0) else (exit 1)                                      # [win]
        - if exist %LIBRARY_PREFIX%\share\cmake\ZeroMQ\ZeroMQConfig.cmake (exit 0) else (exit 1)        # [win]
        - if exist %LIBRARY_PREFIX%\share\cmake\ZeroMQ\ZeroMQConfigVersion.cmake (exit 0) else (exit 1) # [win]
        - test -f ${PREFIX}/lib/libzmq.a                                  # [unix]
        - test -f ${PREFIX}/lib/libzmq.so                                 # [linux]
        - test -f ${PREFIX}/lib/libzmq.so.5                               # [linux]
        - test -f ${PREFIX}/lib/libzmq.dylib                              # [osx]
        - test -f ${PREFIX}/lib/libzmq.dylib.5                            # [osx]
        - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfig.cmake         # [unix]
        - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfigVersion.cmake  # [unix]
about:
    home: http://zeromq.org
    license: LGPL 3
    summary: A high-performance asynchronous messaging library.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - SylvainCorlay
        - JohanMabille
        - gouarin
